export const BUILTIN_EXERCISES = [
  {
    id: 'en1-2025-t1', year: 2025, paper: '英语一', textNo: 1, source: '内置真题',
    title: '2025 英语一 · Text 1', topic: '教育与文学', difficulty: 3,
    passage: `The grammar school boy from Stratford-upon-Avon has landed a scholarly punch after groundbreaking research showed that Shakespeare does benefit children's literacy and emotional development. But only if you act him out.

A study found that a “rehearsal room” approach to teaching Shakespeare broadened children's vocabulary and the complexity of their writing as well as their emotional literacy. “The research shows that the way actors work makes a big difference to the way children use language and also how they think about themselves,” Jacqui O'Hanlon of the Royal Shakespeare Company (RSC), which commissioned the study, said.

The randomised control trial involved hundreds of Year 5 pupils — aged nine and ten — at 45 state primary schools that had not been “previously exposed to RSC pedagogy.” They were split into target and control groups and asked to write, for example, a message in a bottle as Ferdinand after the shipwreck in The Tempest. The target group was given a 30-minute drama-based activity to accompany the passage.

The peer-reviewed results showed that the target group of pupils drew on a wider vocabulary, used words “classed as more sophisticated or rarer,” and wrote at greater length. They also “appear to be more comfortable writing in role ... while [control] pupils imagine how they themselves would react to being shipwrecked, [target] children put themselves in the shoes of a literary character and express that character's emotion.”

The Time to Act study also found that while control pupils relied on “desert island clichés” such as palm trees, target pupils were “more expansive, giving a broader picture of the sky, the sea and the atmospheric conditions.”

O'Hanlon said she had been most surprised by the “emotional literacy” that was evident in the target children's writing and that they were “more resilient in their writing, more hopeful.” She added: “The emotional understanding was very evident and it is probably related to the rehearsal room process where you are used to trying to imagine your way through. They were comfortable in describing different emotional states and part of what you do in drama is put yourself in different shoes.” The study showed the importance of embedding arts in education, she said.

But could the results be replicated with any old dramatist? O'Hanlon said more research would be needed but suggested that Shakespeare's use of 20,000 words, compared with the everyday 2,000 words, gave a “massive expansion of language into children's lives,” which was combined with children “using their whole bodies to bring words to life.”`,
    questions: [
      { id:'25-1-21', number:21, prompt:'The “rehearsal room” approach requires pupils to', options:{A:'rewrite the lines from Shakespeare.',B:"watch RSC actors' performances.",C:'play the roles in Shakespeare.',D:'study drama under RSC artists.'}, answer:'C', type:'细节题', evidence:'But only if you act him out；target group received a drama-based activity.', explanation:'“act him out”和“writing in role”都指向让学生扮演莎士比亚作品中的角色，因此选 C。', trap:'A、B、D 都把“表演式参与”偷换成改写、观看或专业学习。' },
      { id:'25-1-22', number:22, prompt:'The study divided the pupils into two groups to find whether', options:{A:'the change in instruction enhances learning outcomes.',B:'expanding vocabulary helps develop reading fluency.',C:'emotion affects understanding of sophisticated works.',D:'the classroom activity stimulates interest in the arts.'}, answer:'A', type:'实验目的题', evidence:'The target group received an extra drama-based activity; later results compare vocabulary, length and emotional literacy.', explanation:'控制组和实验组唯一关键差异是教学方式，目的就是检验教学方式改变能否提升学习结果，选 A。', trap:'B、C、D 只截取了结果中的局部概念，不能概括实验自变量。' },
      { id:'25-1-23', number:23, prompt:'Control pupils’ reliance on “desert island clichés” shows their', options:{A:'weakness in description.',B:'omission of small details.',C:'casual style of writing.',D:'preference for big words.'}, answer:'A', type:'推断题', evidence:'Target pupils were more expansive and gave a broader picture of the sky, sea and conditions.', explanation:'控制组只写棕榈树等套路意象，与实验组更丰富、更开阔的描述形成反差，说明描述能力较弱，选 A。', trap:'“细节少”只是表象，句子强调的是整体描写的单薄。' },
      { id:'25-1-24', number:24, prompt:"What can promote children's emotional literacy according to O'Hanlon?", options:{A:'Writing in an imaginative manner.',B:'Identifying with literary characters.',C:'Drawing inspiration from nature.',D:'Concentrating on real-life situations.'}, answer:'B', type:'细节题', evidence:'Part of what you do in drama is put yourself in different shoes.', explanation:'“put yourself in different shoes”即代入文学人物、体会人物情绪，选 B。', trap:'A 范围太宽；原文不是泛泛的想象写作，而是角色代入。' },
      { id:'25-1-25', number:25, prompt:'It can be inferred from the last paragraph that', options:{A:'the new teaching method may work best with Shakespeare.',B:'the language of Shakespeare may be formidable for pupils.',C:'other old dramatists may be included in primary education.',D:'pupils may be reluctant to work on other old dramatists.'}, answer:'A', type:'推断题', evidence:"More research is needed for other dramatists; Shakespeare's unusually large vocabulary gives a massive expansion of language.", explanation:'作者保留了对其他剧作家的判断，同时强调莎士比亚词汇量的特殊优势，暗示该方法可能在莎士比亚作品上效果最好，选 A。', trap:'B、C、D 都没有来自末段的充分依据。' }
    ]
  },
  {
    id: 'en2-2025-t1', year: 2025, paper: '英语二', textNo: 1, source: '内置真题',
    title: '2025 英语二 · Text 1', topic: '消费与小费文化', difficulty: 3,
    passage: `U.S. customers historically tipped people they assumed were earning most of their income via tips, such as restaurant servers earning less than the minimum wage. In the early 2010s, a wide range of businesses started processing purchases with iPads and other digital payment systems. These systems prompted customers to tip for services that were not previously tipped.

Today's tip requests are often not connected to the salary and service norms that used to determine when and how people tip. Customers in the past nearly always paid tips after receiving a service, such as at the conclusion of a restaurant meal, after getting a haircut or once a pizza was delivered. That timing could reward high-quality service and give workers an incentive to provide it.

It is becoming more common for tips to be requested beforehand. And new tipping technology may even automatically add tips.

The prevalence of digital payment devices has made it easier to ask customers for a tip. That helps explain why tip requests are creeping into new kinds of services. Customers now routinely see menus of suggested default options — often well above what they expect to owe. The amounts have risen from 10% or less in the 1950s to 15% around the year 2000 to 20% or higher today. This increase is sometimes called tipflation — the expectation of ever-higher tip amounts.

Tipping has always been a vital source of income for workers in historically tipped services, like restaurants, where the tipped minimum wage can be as low as US $2.13 an hour. Tip creep and tipflation are now further supplementing the income of many low-wage service workers.

Notably, tipping primarily benefits some of these workers, but not others such as cooks and dishwashers. To ensure that all employees were paid fair wages, some restaurants banned tipping and increased prices, but this movement toward no-tipping services has largely fizzled out.`,
    questions: [
      { id:'25-2-21', number:21, prompt:'According to Paragraph 1, the practice of tips in the U.S.', options:{A:'was regarded by many customers as a sign of generosity.',B:'was considered essential for waiters.',C:'was a way of rewarding diligence.',D:'was optional in most businesses.'}, answer:'B', type:'细节题', evidence:'Restaurant servers earned less than minimum wage and were assumed to earn most income via tips.', explanation:'传统上服务员收入高度依赖小费，第一段把小费描述为其关键收入来源，因此选 B。', trap:'C 的“奖励服务”出现在第二段，不是第一段信息。' },
      { id:'25-2-22', number:22, prompt:"Compared with tips in the past, today's tips", options:{A:'are paid much less frequently.',B:'are less often requested in advance.',C:'have less to do with service quality.',D:"contribute less to workers' income."}, answer:'C', type:'对比题', evidence:'Today’s requests are often not connected to the salary and service norms; they may be requested beforehand.', explanation:'过去事后给小费可奖励优质服务，如今常在服务前索取，与服务质量的联系减弱，选 C。', trap:'B 与原文相反；A、D 没有依据。' },
      { id:'25-2-23', number:23, prompt:'Tip requests are creeping into new kinds of services as a result of', options:{A:'the advancement of technology.',B:'the desire for income increase.',C:'the diversification of business.',D:'the emergence of tipflation.'}, answer:'A', type:'因果题', evidence:'The prevalence of digital payment devices has made it easier to ask customers for a tip.', explanation:'数字支付设备降低了索要小费的门槛，直接推动小费进入新服务类型，选 A。', trap:'D 是金额上涨现象，不是“进入新服务”的直接原因。' },
      { id:'25-2-24', number:24, prompt:'The movement toward no-tipping services was intended to', options:{A:'promote consumption.',B:'enrich income sources.',C:'maintain reasonable prices.',D:'guarantee income fairness.'}, answer:'D', type:'目的题', evidence:'To ensure that all employees were paid fair wages, some restaurants banned tipping and increased prices.', explanation:'取消小费并涨价的明确目的，是让包括厨师、洗碗工在内的所有员工获得公平工资，选 D。', trap:'“涨价”是手段，不是为了维持低价或促进消费。' },
      { id:'25-2-25', number:25, prompt:'It can be learned from the last paragraph that tipping', options:{A:'does not benefit service workers equally.',B:'helps encourage quality service.',C:'is vital to business development.',D:'reflects the need to reduce prices.'}, answer:'A', type:'推断题', evidence:'Tipping primarily benefits some workers, but not others such as cooks and dishwashers.', explanation:'末段直接说明不同岗位从小费制度中获益不均，选 A。', trap:'B 属于前文传统小费的作用；C、D 均偏离末段。' }
    ]
  },
  {
    id: 'en1-2025-t3', year: 2025, paper: '英语一', textNo: 3, source: '内置真题',
    title: '2025 英语一 · Text 3', topic: '流媒体与数字盗版', difficulty: 4,
    passage: `Ever since taking on Netflix Inc. at its own game, old Hollywood has struggled to turn a profit in streaming, with the likes of Disney+, Peacock and Paramount losing billions of dollars each year, sparking concerns that the services will never be as profitable as cable once was. But the age of streaming has been a boon for some unintended winners: pirates that use software to rip a film or television show in seconds from legitimate online video platforms and host the titles on their own illegitimate services, which rake in about $2 billion annually from ads and subscriptions.

With no video production costs, illegal streaming sites have achieved profit margins approaching 90%, according to the Motion Picture Association (MPA), a trade group representing Hollywood studios that is working to crack down on the thousands of illegal platforms that have cropped up in recent years.

Initially the rise of legitimate online businesses such as Netflix actually helped curb digital piracy, which had largely been based on file uploads. But now piracy involving illegal streaming services as well as file-sharing costs the U.S. economy about $30 billion in lost revenue a year and some 250,000 jobs, estimates the U.S. Chamber of Commerce's Global Innovation Policy Center. The global impact is about $71 billion annually.

“The people who are stealing our movies and our television shows and operating piracy sites are not mom-and-pop operations,” says Charlie Rivkin, chief executive officer of the MPA. “This is organized crime.” Rivkin joined the MPA in 2017 after the organization failed five years earlier to build consensus between Hollywood and Silicon Valley to win passage of legislation in Congress aimed at stopping online piracy. In 2017 the association formed the Alliance for Creativity and Entertainment (ACE), an enforcement taskforce of about 100 detectives circling the globe to help local authorities arrest streaming pirates.

ACE says it has helped shrink the number of illegal streaming services in North America to 126, from more than 1,400 in 2018, aided in part by the MPA's support for a 2020 federal law that made large-scale streaming of copyright material a serious crime.

Consulting firm Parks Associates predicts that legitimate U.S. streaming services' cumulative loss from piracy since 2022 will reach $113 billion in the next two years. “While there is some optimism that emerging countermeasures and best practices may see piracy begin to plateau by 2027, there is no consensus among stakeholders as to when it may begin to decline,” says analyst Steve Hawley.`,
    questions: [
      { id:'25-1-31', number:31, prompt:'According to Paragraph 1, legitimate streaming services', options:{A:'have drawn lessons from Hollywood.',B:'have surpassed cable in revenue.',C:'are unpopular with advertisers.',D:'are confronted with a real threat.'}, answer:'D', type:'细节题', evidence:'Pirates rip titles from legitimate platforms and earn billions on illegitimate services.', explanation:'合法平台的内容被盗版站迅速复制并获利，构成现实威胁，选 D。', trap:'B 与“never as profitable as cable”相反。' },
      { id:'25-1-32', number:32, prompt:'It can be learned that streamers like Netflix', options:{A:'played a part in the fight against illegal file-sharing.',B:'reaped benefits from the war with digital pirates.',C:'promised to become big job creators in the U.S.',D:'used to collaborate with file-uploading platforms.'}, answer:'A', type:'细节题', evidence:'The rise of legitimate online businesses such as Netflix initially helped curb digital piracy based on file uploads.', explanation:'Netflix 等正规流媒体早期曾抑制以文件上传为主的盗版，选 A。', trap:'原文说“helped curb”，并没有合作或从打击中获利。' },
      { id:'25-1-33', number:33, prompt:'It can be inferred from Paragraph 4 that the MPA', options:{A:'was denied cooperation by Silicon Valley.',B:'led a national protest against online piracy.',C:'was urged to form an enforcement taskforce.',D:'failed to win support from local authorities.'}, answer:'A', type:'推断题', evidence:'The organization failed to build consensus between Hollywood and Silicon Valley for anti-piracy legislation.', explanation:'未能在好莱坞与硅谷之间建立共识，意味着硅谷方面的合作支持没有形成，选 A。', trap:'D 偷换对象：后来 ACE 是帮助地方执法，不是地方政府拒绝支持。' },
      { id:'25-1-34', number:34, prompt:'According to Hawley, digital piracy', options:{A:'cannot be checked in spite of new legislation.',B:'will possibly overwhelm legitimate streamers.',C:'is unlikely to diminish in the near future.',D:'has been underestimated by some analysts.'}, answer:'C', type:'观点题', evidence:'There is no consensus as to when piracy may begin to decline; it may only plateau by 2027.', explanation:'短期内最多可能趋于平台期，何时下降仍无共识，因此选 C。', trap:'A 过度绝对；“不能遏制”不是原文观点。' },
      { id:'25-1-35', number:35, prompt:'Which of the following is emphasized in the text?', options:{A:'The need to coordinate anti-piracy action.',B:'The criminal nature of copyright violation.',C:'The prospect of eliminating online piracy.',D:'The economic harm from illegal streaming.'}, answer:'D', type:'主旨题', evidence:'The text repeatedly quantifies illegal profits, lost revenue, jobs and projected cumulative losses.', explanation:'全文用多组金额与就业数据突出非法流媒体造成的经济损失，选 D。', trap:'A、B 是局部信息；C 与末段“不确定下降”相反。' }
    ]
  },
  {
    id: 'en2-2025-t3', year: 2025, paper: '英语二', textNo: 3, source: '内置真题',
    title: '2025 英语二 · Text 3', topic: '高温行动计划', difficulty: 3,
    passage: `Heat action plans, or HAPs, have been proliferating in India in the past few years. In general, a HAP spells out when and how officials should issue heat warnings and alert hospitals and other institutions. Nagpur's plan, for instance, calls for hospitals to set aside “cold wards” in the summer for treating heatstroke patients, and advises builders to give construction laborers a break from work on very hot days.

But implementation of existing HAPs has been uneven, according to a report from the Centre for Policy Research. Many lack adequate funding, it found. And their triggering thresholds often are not customized to the local climate. In some areas, high daytime temperatures alone might serve as an adequate trigger for alerts. But in other places, nighttime temperatures or humidity might be as important a gauge of risk as daytime highs.

Mumbai's April heatstroke deaths highlighted the need for more nuanced and localized warnings, researchers say. That day's high temperature of roughly 36°C was 1°C shy of the heat-wave alert threshold for coastal cities set by national meteorological authorities. But the effects of the heat were amplified by humidity — an often neglected factor in heat alert systems — and the lack of shade at the late-morning outdoor ceremony.

To help improve HAPs, urban planner Rajashree Kotharkar's team is working on a model plan that outlines best practices and could be adapted to local conditions. Among other things, she says, all cities should create a vulnerability map to help focus responses on the populations most at risk.

Such mapping does not need to be complex, Kotharkar says. “A useful map can be created by looking at even a few key parameters.” For example, neighborhoods with a large elderly population or informal dwellings might cope more poorly with heat and could get special warnings or be bolstered with cooling centers. The Nagpur project has already created a risk and vulnerability map, which enabled Kotharkar to tell officials which neighborhoods to focus on in the event of a heat wave this summer.

HAPs should not just include short-term emergency responses, researchers say, but also recommend medium- to long-term measures that could make communities cooler. In Nagpur, for example, Kotharkar's team has been able to advise city officials about where to plant trees to provide shade. HAPs could also guide efforts to retrofit homes or modify building regulations. “Reducing deaths in an emergency is a good target to have, but it is the lowest target,” says climate researcher Chandni Singh.`,
    questions: [
      { id:'25-2-31', number:31, prompt:"According to Paragraph 1, Nagpur's plan proposes measures to", options:{A:'tackle extreme weather.',B:'ensure construction quality.',C:'monitor emergency warnings.',D:'address excessive workloads.'}, answer:'A', type:'细节题', evidence:'Cold wards and work breaks are prescribed for very hot days.', explanation:'设冷病房、极热天气停工休息，都是应对高温极端天气的措施，选 A。', trap:'D 只看到了“休息”，忽略措施服务于高温应对。' },
      { id:'25-2-32', number:32, prompt:'One problem with existing HAPs is that they', options:{A:'prove too costly to be implemented.',B:'lack localized alert-issuing criteria.',C:'give delayed responses to heat waves.',D:'keep hospitals under great pressure.'}, answer:'B', type:'细节题', evidence:'Their triggering thresholds often are not customized to the local climate.', explanation:'预警触发阈值未按当地气候定制，即缺少本地化预警标准，选 B。', trap:'资金不足不等于成本太高；A 偷换概念。' },
      { id:'25-2-33', number:33, prompt:"Mumbai's case shows that India's heat alert systems need to", options:{A:'include other factors besides temperature.',B:'take subtle weather changes into account.',C:'prioritize potentially disastrous heat waves.',D:'draw further support from local authorities.'}, answer:'A', type:'案例题', evidence:'Humidity and lack of shade amplified the heat although temperature stayed below the alert threshold.', explanation:'孟买案例说明仅看温度不够，还要纳入湿度、遮阴等因素，选 A。', trap:'B 的“细微天气变化”过于模糊，未抓住“温度之外的因素”。' },
      { id:'25-2-34', number:34, prompt:'Kotharkar holds that a vulnerability map can help', options:{A:'prevent the harm of high humidity.',B:'target areas needing special attention.',C:"expand the Nagpur project's coverage.",D:'make relief plans for heat-stricken people.'}, answer:'B', type:'细节题', evidence:'The map tells officials which neighborhoods to focus on and identifies populations most at risk.', explanation:'脆弱性地图用于锁定最需要重点关注的人群和社区，选 B。', trap:'D 侧重“制定救助计划”，而原文核心是精准定位。' },
      { id:'25-2-35', number:35, prompt:'According to the last paragraph, researchers believe that HAPs should', options:{A:'focus more on heatstroke treatment.',B:'apply for more government grants.',C:'invite wider public participation.',D:'serve a broader range of purposes.'}, answer:'D', type:'推断题', evidence:'HAPs should include long-term cooling, tree planting, home retrofits and building regulations, not just emergency response.', explanation:'行动计划不能只处理紧急死亡，还应覆盖长期降温、建筑改造等更广目标，选 D。', trap:'A 与“not just short-term emergency responses”相反。' }
    ]
  }
]

export const QUESTION_TYPES = ['细节题','推断题','主旨题','词义句意题','态度题','例证题','因果题','对比题','观点题','目的题','实验目的题','案例题']

